extends: spectral:oas
rules:
  info-contact: off
  oas3-unused-components-schema: off
  oas2-unused-definition: off
except:
  'reference/carts.v3.yml':
    - oas2-oneOf
    - oas2-valid-definition-example
    - oas2-valid-response-schema-example
    - operation-tag-defined
  'reference/catalog.v3.yml':
    - oas2-operation-security-defined
    - oas3-schema
    - oas2-schema
    - oas2-valid-definition-example
    - oas2-valid-response-schema-example
    - oas2-valid-response-example
    - oas2-valid-parameter-example
  'reference/channels.v3.yml':
    - operation-operationId
    - oas3-schema
    - oas3-valid-oas-content-example
  'reference/checkouts.sf.yml':
    - oas2-valid-response-example
  'reference/checkouts.v3.yml':
    - no-$ref-siblings
    - oas2-schema
    - oas2-operation-security-defined
    - oas2-valid-response-schema-example
    - oas2-valid-response-example
    - operation-parameters
  'reference/currencies.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-schema-example
    - operation-operationId
    - no-$ref-siblings
  'reference/current_customer.yml':
    - operation-2xx-response
  'reference/custom-template-associations.v3.yml':
    - openapi-tags
    - operation-tag-defined
  'reference/customer_login.yml':
    - operation-operationId
    - operation-2xx-response
  'reference/customers.v2.yml':
    - oas2-valid-response-schema-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-definition-example
  'reference/email_templates.v3.yml':
    - oas3-schema
    - operation-tag-defined
    - openapi-tags
  'reference/form_fields.sf.yml':
    - operation-operationId
  'reference/geography.v2.yml':
    - operation-operationId
    - oas2-valid-response-example
  'reference/marketing.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-response-schema-example
    - operation-operationId
  'reference/orders.sf.yml':
    - operation-tag-defined
    - oas3-valid-schema-example
  'reference/orders.v2.oas2.yml':
    - oas3-valid-schema-example
    - oas3-valid-oas-content-example
    - oas3-schema
  'reference/orders.v3.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-anyOf
  'reference/payment_methods.v2.yml':
    - operation-operationId
  'reference/price_lists.v3.yml':
    - oas2-schema
    - oas2-valid-response-example
  'reference/pricing.sf.yml':
    - oas2-valid-response-example
    - oas2-schema
    - no-$ref-siblings
  'reference/redirects.v3.yml':
    - oas2-valid-response-example
    - oas2-schema
    - no-$ref-siblings
  'reference/settings.v3.yml':
    - oas3-valid-oas-content-example
    - operation-operationId
  'reference/shipping.v2.yml':
    - oas2-valid-response-schema-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-definition-example
    - typed-enum
    - operation-operationId
  'reference/shipping.v3.yml':
    - oas2-valid-definition-example
    - operation-operationId
    - typed-enum
  'reference/sites.v3.yml':
    - oas2-valid-response-example
    - operation-operationId
  'reference/store_content.v2.yml':
    - oas2-valid-response-example
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-schema-example
  'reference/store_information.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-response-example
    - operation-operationId
    - oas2-valid-response-schema-example
  'reference/storefront_tokens.v3.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
  'reference/subscriptions.sf.yml':
    - operation-operationId
  'reference/tax_classes.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-response-example
    - oas2-valid-response-schema-example
  'reference/themes.v3.yml':
    - oas3-schema
    - operation-operationId
  'reference/webhooks.v3.yml':
    - oas3-valid-oas-content-example
  'reference/widgets.v3.yml':
    - typed-enum
    - oas2-anyOf
    - oas2-valid-response-example
  'reference/wishlists.v3.yml':
    - oas2-valid-definition-example
    - oas2-valid-response-example
    - oas2-valid-response-schema-example
  'reference/checkouts.sf.yml#/host':
    - oas2-schema
  'reference/form_fields.sf.yml#/host':
    - oas2-schema
  'reference/orders.sf.yml#/host':
    - oas2-schema
  'reference/subscriptions.sf.yml#/host':
    - oas2-schema
  'reference/current_customer.yml#/host':
    - oas2-schema
  'reference/customer_login.yml#/host':
    - oas2-schema
  'reference/shipping_provider.yml#/host':
    - oas2-schema
  'carts.v3.yml':
    - oas2-oneOf
    - oas2-valid-definition-example
    - oas2-valid-response-schema-example
    - operation-tag-defined
  'catalog.v3.yml':
    - oas2-operation-security-defined
    - oas3-schema
    - oas2-schema
    - oas2-valid-definition-example
    - oas2-valid-response-schema-example
    - oas2-valid-response-example
    - oas2-valid-parameter-example
  'channels.v3.yml':
    - operation-operationId
    - oas3-schema
    - oas3-valid-oas-content-example
  'checkouts.sf.yml':
    - oas2-valid-response-example
  'checkouts.v3.yml':
    - no-$ref-siblings
    - oas2-schema
    - oas2-operation-security-defined
    - oas2-valid-response-schema-example
    - oas2-valid-response-example
    - operation-parameters
  'currencies.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-schema-example
    - operation-operationId
    - no-$ref-siblings
  'current_customer.yml':
    - operation-2xx-response
  'custom-template-associations.v3.yml':
    - openapi-tags
    - operation-tag-defined
  'customer_login.yml':
    - operation-operationId
    - operation-2xx-response
  'customers.v2.yml':
    - oas2-valid-response-schema-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-definition-example
  'email_templates.v3.yml':
    - oas3-schema
    - operation-tag-defined
    - openapi-tags
  'form_fields.sf.yml':
    - operation-operationId
  'geography.v2.yml':
    - operation-operationId
    - oas2-valid-response-example
  'marketing.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-response-schema-example
    - operation-operationId
  'orders.sf.yml':
    - operation-tag-defined
    - oas3-valid-schema-example
  'orders.v2.oas2.yml':
    - oas3-valid-schema-example
    - oas3-valid-oas-content-example
    - oas3-schema
  'orders.v3.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-anyOf
  'payment_methods.v2.yml':
    - operation-operationId
  'price_lists.v3.yml':
    - oas2-schema
    - oas2-valid-response-example
  'pricing.sf.yml':
    - oas2-valid-response-example
    - oas2-schema
    - no-$ref-siblings
  'redirects.v3.yml':
    - oas2-valid-response-example
    - oas2-schema
    - no-$ref-siblings
  'settings.v3.yml':
    - oas3-valid-oas-content-example
    - operation-operationId
  'shipping.v2.yml':
    - oas2-valid-response-schema-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-definition-example
    - typed-enum
    - operation-operationId
  'shipping.v3.yml':
    - oas2-valid-definition-example
    - operation-operationId
    - typed-enum
  'sites.v3.yml':
    - oas2-valid-response-example
    - operation-operationId
  'store_content.v2.yml':
    - oas2-valid-response-example
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
    - oas2-valid-response-schema-example
  'store_information.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-response-example
    - operation-operationId
    - oas2-valid-response-schema-example
  'storefront_tokens.v3.yml':
    - oas2-valid-definition-example
    - oas2-valid-parameter-example
  'subscriptions.sf.yml':
    - operation-operationId
  'tax_classes.v2.yml':
    - oas2-valid-definition-example
    - oas2-valid-response-example
    - oas2-valid-response-schema-example
  'themes.v3.yml':
    - oas3-schema
    - operation-operationId
  'webhooks.v3.yml':
    - oas3-valid-oas-content-example
  'widgets.v3.yml':
    - typed-enum
    - oas2-anyOf
    - oas2-valid-response-example
  'wishlists.v3.yml':
    - oas2-valid-definition-example
    - oas2-valid-response-example
    - oas2-valid-response-schema-example
  'checkouts.sf.yml#/host':
    - oas2-schema
  'form_fields.sf.yml#/host':
    - oas2-schema
  'orders.sf.yml#/host':
    - oas2-schema
  'subscriptions.sf.yml#/host':
    - oas2-schema
  'current_customer.yml#/host':
    - oas2-schema
  'customer_login.yml#/host':
    - oas2-schema
  'shipping_provider.yml#/host':
    - oas2-schema
  'reference/customers_v2.yml':
    - oas2-valid-response-schema-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-definition-example
  'customers_v2.yml':
    - oas2-valid-response-schema-example
    - oas2-valid-parameter-example
    - oas2-valid-response-example
    - oas2-valid-definition-example