swagger: '2.0'
info:
  title: Storefront Form Fields (Beta)
  description: |-
    Read form fields on a BigCommerce hosted storefront.

    <div class="HubBlock--callout">
    <div class="CalloutBlock--warning">
    <div class="HubBlock-content">

    > ### Note
    > * Breaking changes may be introduced to this endpoint while in beta.

    </div>
    </div>
    </div>
  version: ''
consumes:
  - application/json
produces:
  - application/json
paths:
  /form-fields:
    get:
      description: |-
        Gets form fields.

        <div class="HubBlock--callout">
        <div class="CalloutBlock--info">
        <div class="HubBlock-content"> 

        > ### Note
        > The Send a Test Request feature is not currently supported for this endpoint.
         
        </div>
        </div>
        </div>
      parameters:
        - name: filter
          in: query
          schema:
            type: string
            enum:
              - customerAccount
              - shippingAddress
              - billingAddress
      responses:
        '200':
          description: Returns an object with form fields groups.
          schema:
            $ref: '#/definitions/FormFieldGroups'
          examples:
            application/json:
              customerAccount:
                - id: Excepteur
                  name: laboris minim reprehenderit
                  custom: false
                  label: Lorem
                  required: false
                  default: dolore
                  type: date
                  fieldType: radio
                  min: in Excepteur enim fugiat al
                  max: commodo
                  maxLength: -69844252
                  secret: false
                  options:
                    helperLabel: nulla
                    items:
                      value: fugiat sint est in in
                      label: sit velit
              shippingAddress:
                - id: sint
                  name: ex ut Duis veniam qui
                  custom: true
                  label: magna
                  required: true
                  default: veniam
                  type: string
                  fieldType: checkbox
                  min: tempor ut
                  max: ea reprehenderit in
                  maxLength: 528845
                  secret: true
                  options:
                    helperLabel: eiusmod exercitation
                    items:
                      value: deserunt exerc
                      label: enim ad id
              billingAddress:
                - id: cupidatat
                  name: laborum fugiat
                  custom: false
                  label: id reprehenderit dolore
                  required: true
                  default: ipsum dolore
                  type: array
                  fieldType: date
                  min: adipisicing ipsum nost
                  max: sit aute cillum commodo
                  maxLength: -98777935
                  secret: true
                  options:
                    helperLabel: labore fugiat in
                    items:
                      value: ad dolor
                      label: pariatur
                - id: ea in Lorem adipisici
                  name: mollit tempor Lorem incididunt nulla
                  custom: false
                  label: Ut ut Excepteur eiusmod quis
                  required: false
                  default: esse
                  type: date
                  fieldType: radio
                  min: veniam pariatur et
                  max: Lorem Excepteur ad sint
                  maxLength: 82281003
                  secret: false
                  options:
                    helperLabel: culpa id consequat
                    items:
                      value: consectetur incididunt Duis deserunt Ut
                      label: sunt in
                - id: labore aute elit in sed
                  name: ea magna dolor aute
                  custom: true
                  label: incididunt minim
                  required: true
                  default: in commodo
                  type: string
                  fieldType: radio
                  min: sunt
                  max: quis culpa cupidatat pariatur sunt
                  maxLength: 68647948
                  secret: true
                  options:
                    helperLabel: moll
                    items:
                      value: elit velit occaecat cupidatat
                      label: ex in ut nulla
                - id: qui fugiat velit Excepteur et
                  name: enim dolor quis in
                  custom: true
                  label: laborum cupidatat elit sed
                  required: true
                  default: cillum
                  type: integer
                  fieldType: radio
                  min: incididunt irure aliquip
                  max: commodo sunt minim occaecat
                  maxLength: 77216978
                  secret: false
                  options:
                    helperLabel: nulla
                    items:
                      value: minim ad reprehenderit est
                      label: sint
      tags:
        - Form Fields
      summary: Get Form Fields
definitions:
  FormFieldGroups:
    type: object
    description: Group of form field groups
    properties:
      customerAccount:
        $ref: '#/definitions/FormFields'
      shippingAddress:
        $ref: '#/definitions/FormFields'
      billingAddress:
        $ref: '#/definitions/FormFields'
  FormFields:
    type: array
    description: List of form fields for the group
    items:
      $ref: '#/definitions/FormField'
  FormField:
    type: object
    description: Form Field
    properties:
      id:
        type: string
        description: Field unique ID
      name:
        type: string
        description: Field name
      custom:
        type: boolean
        description: Wether is a custom field or system built-in field.
      label:
        type: string
        description: User-friendly label
      required:
        type: boolean
        description: Wether this field is required or not
      default:
        nullable: true
        type: string
        description: The field unique ID
      type:
        nullable: true
        type: string
        description: Type of the value hold by the field
        enum:
          - integer
          - string
          - array
          - date
      fieldType:
        nullable: true
        type: string
        description: Type of the field
        enum:
          - checkbox
          - text
          - date
          - multiline
          - radio
          - dropdown
      min:
        nullable: true
        type: string
        description: The minimun valid value for the field (integer and date type only)
      max:
        nullable: true
        type: string
        description: The minimun valid value for the field (integer and date type only)
      maxLength:
        nullable: true
        type: integer
        description: The maximum length for the value (string type only)
      secret:
        nullable: true
        type: boolean
        description: Whether the field represents a password field
      options:
        nullable: true
        type: object
        description: 'Extra data for radio, dropdown and checkbox field types.'
        properties:
          helperLabel:
            nullable: true
            type: string
            description: Placeholder text for dropdown field type.
          items:
            type: object
            description: List of possible values for this field.
            properties:
              value:
                type: string
                description: Field option value.
              label:
                type: string
                description: User friendly label.
tags:
  - name: Form Fields
basePath: /api/storefront
host: '{$$.env.store_domain}'
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
schemes:
  - https
