type: object
properties:
  review:
    type: object
    properties:
      products:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            sku:
              type: string
            link:
              type: string
      unsubscribe_link:
        type: string
  store:
    type: object
    properties:
      name:
        type: string
      domain_name:
        type: string
      logo:
        type: object
        properties:
          title:
            type: string
          name:
            type: string
          url:
            type: string
      ssl_path:
        type: string
      cdn_path:
        type: string
      image_directory:
        type: string
      img_path:
        type: string
      path_normal:
        type: string
      path:
        type: string
      address:
        type: string
      language:
        type: object
        properties:
          code:
            type: string
          direction:
            type: string
  customer:
    type: object
    properties:
      first_name:
        type: string
      full_name:
        type: string
      email:
        type: string
  misc:
    type: object
    properties:
      year:
        type: integer
  translations:
    type: object
    properties:
      en:
        type: object
        properties:
          title:
            type: string
          hello:
            type: string
          message:
            type: string
          instruction:
            type: string
          review_text:
            type: string
          thanks:
            type: string
          go_shopping:
            type: string

