name: Run Spectral on Pull Requests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: 'reference/*.yml'
